import { createSlice } from '@reduxjs/toolkit'
import type { RootState } from '../../app/store'
//assets
import {  patient1 , patient2 , patient3} from '../../assets'

const initialState = [
    {
        id :1,
        title :"Root Canal",
        date :"Dec 22,2023",
        time :"12:00Pm",
        patient : "SEDDIK MOUNIR",
        location :"Oran",
        payWith :"Debit Card",
        payFrom:'Oran Bank',
        payOn :"jan 12, 2023 At 09:00 AM",
        status :"Success",
        medicalCheckUp :500,
        medicine :20,
        icon: patient1
    },
    {
        id :2,
        title :"Monthly Medical Check-up",
        date :"Dec 22,2023",
        time :"12:00Pm",
        patient : "John Smith",
        location :"Algiers",
        payWith :"Debit Card",
        payFrom:'Oran Bank',
        payOn :"jan 12, 2023 At 09:00 AM",
        from: "Algiers",
        status :"Pending",
        medicalCheckUp :500,
        medicine :20,
        icon: patient2
    },
    {
        id :3,
        title :"Diabetes Control Appointment",
        date :"Dec 22,2023",
        time :"12:00Pm",
        patient : "Maia Rodriguez",
        location :"Oran",
        payWith :"Debit Card",
        payFrom:'Oran Bank',
        payOn :"jan 12, 2023 At 09:00 AM",
        from: "Oran",
        status :"Canceled",
        medicalCheckUp :500,
        medicine :20,
        icon : patient3
    },
    {
        id :4,
        title :"Root Canal",
        date :"Dec 22,2023",
        time :"12:00Pm",
        patient : "SEDDIK MOUNIR",
        location :"Oran",
        payWith :"Debit Card",
        payFrom:'Oran Bank',
        payOn :"jan 12, 2023 At 09:00 AM",
        status :"Success",
        medicalCheckUp :500,
        medicine :20,
        icon: patient1
    },
    {
        id :5,
        title :"Monthly Medical Check-up",
        date :"Dec 22,2023",
        time :"12:00Pm",
        patient : "John Smith",
        location :"Algiers",
        payWith :"Debit Card",
        payFrom:'Oran Bank',
        payOn :"jan 12, 2023 At 09:00 AM",
        from: "Algiers",
        status :"Pending",
        medicalCheckUp :500,
        medicine :20,
        icon: patient2
    },
    {
        id :6,
        title :"Diabetes Control Appointment",
        date :"Dec 22,2023",
        time :"12:00Pm",
        patient : "Maia Rodriguez",
        location :"Oran",
        payWith :"Debit Card",
        payFrom:'Oran Bank',
        payOn :"jan 12, 2023 At 09:00 AM",
        from: "Oran",
        status :"Canceled",
        medicalCheckUp :500,
        medicine :20,
        icon : patient3
    },
    {
        id :7,
        title :"Root Canal",
        date :"Dec 22,2023",
        time :"12:00Pm",
        patient : "SEDDIK MOUNIR",
        location :"Oran",
        payWith :"Debit Card",
        payFrom:'Oran Bank',
        payOn :"jan 12, 2023 At 09:00 AM",
        status :"Success",
        medicalCheckUp :500,
        medicine :20,
        icon: patient1
    },
    {
        id :8,
        title :"Monthly Medical Check-up",
        date :"Dec 22,2023",
        time :"12:00Pm",
        patient : "John Smith",
        location :"Algiers",
        payWith :"Debit Card",
        payFrom:'Oran Bank',
        payOn :"jan 12, 2023 At 09:00 AM",
        from: "Algiers",
        status :"Pending",
        medicalCheckUp :500,
        medicine :20,
        icon: patient2
    },
    {
        id :9,
        title :"Diabetes Control Appointment",
        date :"Dec 22,2023",
        time :"12:00Pm",
        patient : "Maia Rodriguez",
        location :"Oran",
        payWith :"Debit Card",
        payFrom:'Oran Bank',
        payOn :"jan 12, 2023 At 09:00 AM",
        from: "Oran",
        status :"Canceled",
        medicalCheckUp :500,
        medicine :20,
        icon : patient3
    },
    {
        id :10,
        title :"Root Canal",
        date :"Dec 22,2023",
        time :"12:00Pm",
        patient : "SEDDIK MOUNIR",
        location :"Oran",
        payWith :"Debit Card",
        payFrom:'Oran Bank',
        payOn :"jan 12, 2023 At 09:00 AM",
        status :"Success",
        medicalCheckUp :500,
        medicine :20,
        icon: patient1
    },
    {
        id :11,
        title :"Monthly Medical Check-up",
        date :"Dec 22,2023",
        time :"12:00Pm",
        patient : "John Smith",
        location :"Algiers",
        payWith :"Debit Card",
        payFrom:'Oran Bank',
        payOn :"jan 12, 2023 At 09:00 AM",
        from: "Algiers",
        status :"Pending",
        medicalCheckUp :500,
        medicine :20,
        icon: patient2
    },
    {
        id :12,
        title :"Diabetes Control Appointment",
        date :"Dec 22,2023",
        time :"12:00Pm",
        patient : "Maia Rodriguez",
        location :"Oran",
        payWith :"Debit Card",
        payFrom:'Oran Bank',
        payOn :"jan 12, 2023 At 09:00 AM",
        from: "Oran",
        status :"Canceled",
        medicalCheckUp :500,
        medicine :20,
        icon : patient3
    },
    {
        id :13,
        title :"Root Canal",
        date :"Dec 22,2023",
        time :"12:00Pm",
        patient : "SEDDIK MOUNIR",
        location :"Oran",
        payWith :"Debit Card",
        payFrom:'Oran Bank',
        payOn :"jan 12, 2023 At 09:00 AM",
        status :"Success",
        medicalCheckUp :500,
        medicine :20,
        icon: patient1
    },
    {
        id :14,
        title :"Monthly Medical Check-up",
        date :"Dec 22,2023",
        time :"12:00Pm",
        patient : "John Smith",
        location :"Algiers",
        payWith :"Debit Card",
        payFrom:'Oran Bank',
        payOn :"jan 12, 2023 At 09:00 AM",
        from: "Algiers",
        status :"Pending",
        medicalCheckUp :500,
        medicine :20,
        icon: patient2
    },
    {
        id :15,
        title :"Diabetes Control Appointment",
        date :"Dec 22,2023",
        time :"12:00Pm",
        patient : "Maia Rodriguez",
        location :"Oran",
        payWith :"Debit Card",
        payFrom:'Oran Bank',
        payOn :"jan 12, 2023 At 09:00 AM",
        from: "Oran",
        status :"Canceled",
        medicalCheckUp :500,
        medicine :20,
        icon : patient3
    },
    {
        id :16,
        title :"Root Canal",
        date :"Dec 22,2023",
        time :"12:00Pm",
        patient : "SEDDIK MOUNIR",
        location :"Oran",
        payWith :"Debit Card",
        payFrom:'Oran Bank',
        payOn :"jan 12, 2023 At 09:00 AM",
        status :"Success",
        medicalCheckUp :500,
        medicine :20,
        icon: patient1
    },
    {
        id :17,
        title :"Monthly Medical Check-up",
        date :"Dec 22,2023",
        time :"12:00Pm",
        patient : "John Smith",
        location :"Algiers",
        payWith :"Debit Card",
        payFrom:'Oran Bank',
        payOn :"jan 12, 2023 At 09:00 AM",
        from: "Algiers",
        status :"Pending",
        medicalCheckUp :500,
        medicine :20,
        icon: patient2
    },
    {
        id :18,
        title :"Diabetes Control Appointment",
        date :"Dec 22,2023",
        time :"12:00Pm",
        patient : "Maia Rodriguez",
        location :"Oran",
        payWith :"Debit Card",
        payFrom:'Oran Bank',
        payOn :"jan 12, 2023 At 09:00 AM",
        from: "Oran",
        status :"Canceled",
        medicalCheckUp :500,
        medicine :20,
        icon : patient3
    },
    
]

export const appointmentsSlice = createSlice({
  name: 'appointments',
  initialState,
  reducers: {},
})

export const selectAppointments = (state: RootState) => state.appointments

export default appointmentsSlice.reducer