import { createSlice } from '@reduxjs/toolkit'
import type { RootState } from '../../app/store'
//assets
import {  patient1 , patient2 , patient3 , patient4 , patient5 , patient6 , patient7} from '../../assets'

const initialState = [
    {
        id: 1,
        fullName:"Sarah Lee",
        address:"321 Maple st, anytown, USA",
        picture: patient1,
        appointments: 15,
        completedAppointments: 12,
        weight: "160lb",
        height: "1,80m",
        bloodType: "o- (Negative)",
        BloodGlucose : "92mg/dl",
        bloodPressure: "120/80mmHg",
        disease: "Diabetes",
        allergies : "Peanuts",
        appointmentsNotes: [
            {
                id:1,
                date:"March 22,2023",
                title: "Diabetes Control Appointment",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Check-up",
                duration:"3 months",
                document:"check-up-result.pdf",
            },
            {
                id:2,
                date:"March 22,2022",
                title: "X-ray scanning bones",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
            {
                id:3,
                date:"March 22,2022",
                title: "Diabetes Consultation",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
        ]
    },
    {
        id: 2,
        fullName:"Jane Doe",
        address:"456 Elm st, anytown, USA",
        picture: patient2,
        appointments: 15,
        completedAppointments: 12,
        weight: "160lb",
        height: "1,80m",
        bloodType: "o- (Negative)",
        BloodGlucose : "92mg/dl",
        bloodPressure: "120/80mmHg",
        disease: "Diabetes",
        allergies : "Peanuts",
        appointmentsNotes: [
            {
                id:1,
                date:"March 22,2023",
                title: "Diabetes Control Appointment",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Check-up",
                duration:"3 months",
                document:"check-up-result.pdf",
            },
            {
                id:2,
                date:"March 22,2022",
                title: "X-ray scanning bones",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
            {
                id:3,
                date:"March 22,2022",
                title: "Diabetes Consultation",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
        ]
    },
    {
        id: 3,
        fullName:"Mark Brown",
        address:"456 Elm st, anytown, USA",
        picture: patient3,
        appointments: 15,
        completedAppointments: 12,
        weight: "160lb",
        height: "1,80m",
        bloodType: "o- (Negative)",
        BloodGlucose : "92mg/dl",
        bloodPressure: "120/80mmHg",
        disease: "Diabetes",
        allergies : "Peanuts",
        appointmentsNotes: [
            {
                id:1,
                date:"March 22,2023",
                title: "Diabetes Control Appointment",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Check-up",
                duration:"3 months",
                document:"check-up-result.pdf",
            },
            {
                id:2,
                date:"March 22,2022",
                title: "X-ray scanning bones",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
            {
                id:3,
                date:"March 22,2022",
                title: "Diabetes Consultation",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
        ]
    },
    {
        id: 4,
        fullName:"John Smith",
        address:"456 Elm st, anytown, USA",
        picture: patient4,
        appointments: 15,
        completedAppointments: 12,
        weight: "160lb",
        height: "1,80m",
        bloodType: "o- (Negative)",
        BloodGlucose : "92mg/dl",
        bloodPressure: "120/80mmHg",
        disease: "Diabetes",
        allergies : "Peanuts",
        appointmentsNotes: [
            {
                id:1,
                date:"March 22,2023",
                title: "Diabetes Control Appointment",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Check-up",
                duration:"3 months",
                document:"check-up-result.pdf",
            },
            {
                id:2,
                date:"March 22,2022",
                title: "X-ray scanning bones",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
            {
                id:3,
                date:"March 22,2022",
                title: "Diabetes Consultation",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
        ]
    },
    {
        id: 5,
        fullName:"Mark Brown",
        address:"456 Elm st, anytown, USA",
        picture: patient5,
        appointments: 15,
        completedAppointments: 12,
        weight: "160lb",
        height: "1,80m",
        bloodType: "o- (Negative)",
        BloodGlucose : "92mg/dl",
        bloodPressure: "120/80mmHg",
        disease: "Diabetes",
        allergies : "Peanuts",
        appointmentsNotes: [
            {
                id:1,
                date:"March 22,2023",
                title: "Diabetes Control Appointment",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Check-up",
                duration:"3 months",
                document:"check-up-result.pdf",
            },
            {
                id:2,
                date:"March 22,2022",
                title: "X-ray scanning bones",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
            {
                id:3,
                date:"March 22,2022",
                title: "Diabetes Consultation",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
        ]
    },
    {
        id: 6,
        fullName:"Mark Brown",
        address:"456 Elm st, anytown, USA",
        picture: patient6,
        appointments: 15,
        completedAppointments: 12,
        weight: "160lb",
        height: "1,80m",
        bloodType: "o- (Negative)",
        BloodGlucose : "92mg/dl",
        bloodPressure: "120/80mmHg",
        disease: "Diabetes",
        allergies : "Peanuts",
        appointmentsNotes: [
            {
                id:1,
                date:"March 22,2023",
                title: "Diabetes Control Appointment",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Check-up",
                duration:"3 months",
                document:"check-up-result.pdf",
            },
            {
                id:2,
                date:"March 22,2022",
                title: "X-ray scanning bones",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
            {
                id:3,
                date:"March 22,2022",
                title: "Diabetes Consultation",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
        ]
    },
    {
        id: 7,
        fullName:"Mark Brown",
        address:"456 Elm st, anytown, USA",
        picture: patient7,
        appointments: 15,
        completedAppointments: 12,
        weight: "160lb",
        height: "1,80m",
        bloodType: "o- (Negative)",
        BloodGlucose : "92mg/dl",
        bloodPressure: "120/80mmHg",
        disease: "Diabetes",
        allergies : "Peanuts",
        appointmentsNotes: [
            {
                id:1,
                date:"March 22,2023",
                title: "Diabetes Control Appointment",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Check-up",
                duration:"3 months",
                document:"check-up-result.pdf",
            },
            {
                id:2,
                date:"March 22,2022",
                title: "X-ray scanning bones",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
            {
                id:3,
                date:"March 22,2022",
                title: "Diabetes Consultation",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
        ]
    },
    {
        id: 8,
        fullName:"Mark Brown",
        address:"456 Elm st, anytown, USA",
        picture: patient3,
        appointments: 15,
        completedAppointments: 12,
        weight: "160lb",
        height: "1,80m",
        bloodType: "o- (Negative)",
        BloodGlucose : "92mg/dl",
        bloodPressure: "120/80mmHg",
        disease: "Diabetes",
        allergies : "Peanuts",
        appointmentsNotes: [
            {
                id:1,
                date:"March 22,2023",
                title: "Diabetes Control Appointment",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Check-up",
                duration:"3 months",
                document:"check-up-result.pdf",
            },
            {
                id:2,
                date:"March 22,2022",
                title: "X-ray scanning bones",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
            {
                id:3,
                date:"March 22,2022",
                title: "Diabetes Consultation",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
        ]
    },
    {
        id: 9,
        fullName:"Mark Brown",
        address:"456 Elm st, anytown, USA",
        picture: patient5,
        appointments: 15,
        completedAppointments: 12,
        weight: "160lb",
        height: "1,80m",
        bloodType: "o- (Negative)",
        BloodGlucose : "92mg/dl",
        bloodPressure: "120/80mmHg",
        disease: "Diabetes",
        allergies : "Peanuts",
        appointmentsNotes: [
            {
                id:1,
                date:"March 22,2023",
                title: "Diabetes Control Appointment",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Check-up",
                duration:"3 months",
                document:"check-up-result.pdf",
            },
            {
                id:2,
                date:"March 22,2022",
                title: "X-ray scanning bones",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
            {
                id:3,
                date:"March 22,2022",
                title: "Diabetes Consultation",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
        ]
    },
    {
        id: 10,
        fullName:"Mark Brown",
        address:"456 Elm st, anytown, USA",
        picture: patient1,
        appointments: 15,
        completedAppointments: 12,
        weight: "160lb",
        height: "1,80m",
        bloodType: "o- (Negative)",
        BloodGlucose : "92mg/dl",
        bloodPressure: "120/80mmHg",
        disease: "Diabetes",
        allergies : "Peanuts",
        appointmentsNotes: [
            {
                id:1,
                date:"March 22,2023",
                title: "Diabetes Control Appointment",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Check-up",
                duration:"3 months",
                document:"check-up-result.pdf",
            },
            {
                id:2,
                date:"March 22,2022",
                title: "X-ray scanning bones",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
            {
                id:3,
                date:"March 22,2022",
                title: "Diabetes Consultation",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
        ]
    },
    {
        id: 11,
        fullName:"Mark Brown",
        address:"456 Elm st, anytown, USA",
        picture: patient7,
        appointments: 15,
        completedAppointments: 12,
        weight: "160lb",
        height: "1,80m",
        bloodType: "o- (Negative)",
        BloodGlucose : "92mg/dl",
        bloodPressure: "120/80mmHg",
        disease: "Diabetes",
        allergies : "Peanuts",
        appointmentsNotes: [
            {
                id:1,
                date:"March 22,2023",
                title: "Diabetes Control Appointment",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Check-up",
                duration:"3 months",
                document:"check-up-result.pdf",
            },
            {
                id:2,
                date:"March 22,2022",
                title: "X-ray scanning bones",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
            {
                id:3,
                date:"March 22,2022",
                title: "Diabetes Consultation",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
        ]
    },
    {
        id: 12,
        fullName:"Mark Brown",
        address:"456 Elm st, anytown, USA",
        picture: patient4,
        appointments: 15,
        completedAppointments: 12,
        weight: "160lb",
        height: "1,80m",
        bloodType: "o- (Negative)",
        BloodGlucose : "92mg/dl",
        bloodPressure: "120/80mmHg",
        disease: "Diabetes",
        allergies : "Peanuts",
        appointmentsNotes: [
            {
                id:1,
                date:"March 22,2023",
                title: "Diabetes Control Appointment",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Check-up",
                duration:"3 months",
                document:"check-up-result.pdf",
            },
            {
                id:2,
                date:"March 22,2022",
                title: "X-ray scanning bones",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
            {
                id:3,
                date:"March 22,2022",
                title: "Diabetes Consultation",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
        ]
    },
    {
        id: 13,
        fullName:"Mark Brown",
        address:"456 Elm st, anytown, USA",
        picture: patient5,
        appointments: 15,
        completedAppointments: 12,
        weight: "160lb",
        height: "1,80m",
        bloodType: "o- (Negative)",
        BloodGlucose : "92mg/dl",
        bloodPressure: "120/80mmHg",
        disease: "Diabetes",
        allergies : "Peanuts",
        appointmentsNotes: [
            {
                id:1,
                date:"March 22,2023",
                title: "Diabetes Control Appointment",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Check-up",
                duration:"3 months",
                document:"check-up-result.pdf",
            },
            {
                id:2,
                date:"March 22,2022",
                title: "X-ray scanning bones",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
            {
                id:3,
                date:"March 22,2022",
                title: "Diabetes Consultation",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
        ]
    },
    {
        id: 14,
        fullName:"Mark Brown",
        address:"456 Elm st, anytown, USA",
        picture: patient6,
        appointments: 15,
        completedAppointments: 12,
        weight: "160lb",
        height: "1,80m",
        bloodType: "o- (Negative)",
        BloodGlucose : "92mg/dl",
        bloodPressure: "120/80mmHg",
        disease: "Diabetes",
        allergies : "Peanuts",
        appointmentsNotes: [
            {
                id:1,
                date:"March 22,2023",
                title: "Diabetes Control Appointment",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Check-up",
                duration:"3 months",
                document:"check-up-result.pdf",
            },
            {
                id:2,
                date:"March 22,2022",
                title: "X-ray scanning bones",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
            {
                id:3,
                date:"March 22,2022",
                title: "Diabetes Consultation",
                content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis animi, labore consequatur consectetur consequuntur ",
                treatment:"Scanning",
                duration:"2 months",
                document:"X-ray-scan.pdf",
            },
        ]
    },
]

export const patientsSlice = createSlice({
  name: 'patients',
  initialState,
  reducers: {},

})
export const selectPatients = (state: RootState) => state.patients
export const selectPatientById = (state: RootState, id: number) => {
    return state.patients.find(patient => patient.id === id);
  };

export default patientsSlice.reducer